
spring:
  datasource:
    #url: jdbc:sqlite:data.db
    url: jdbc:sqlite:data.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9090
attach:
  folder: /JAVACourseDesign/JavaCourseDesign/
  #folder: /teach/