@startuml

title 学生管理系统功能架构

package "学生端" {
    package "主界面" {
        [待办（作业提交）]
        [日程表]
    }
    package "课程信息" {
        [课程信息查看]
    }
    [课程申请]
    package "个人信息" {
        [个人信息查询]
        [个人信息修改]
        [荣誉信息]
        [消费信息]
    }
    package "学生请假" {
        [请假申请]
        [批准情况]
    }
    [创新实践]
    [日常活动]
    package "成绩查询" {
        [单科成绩查询]
    }
}

package "教师端" {

}

package "管理员端" {

}

@enduml