@startuml

package "client (JavaFX)" {
    [界面]
    [StudentInfoPane.java]
    [StudentInfoPane.fxml]
}

package "server (Spring Boot)" {
    [StudentController.java]
    [Student.java]
    [StudentRepository.java]
}

database "database" {
    [data.db]
}

[StudentInfoPane.java] --> [界面]
[StudentInfoPane.fxml] --> [界面]
[StudentInfoPane.fxml] --> [StudentInfoPane.java]

[界面] --> [用户]

[StudentInfoPane.java] --> [StudentController.java]
[StudentController.java] --> [Student.java]
[StudentController.java] --> [StudentRepository.java]

[StudentRepository.java] --> [data.db]

@enduml